# Model arguments
model_name_or_path: Qwen/Qwen2.5-0.5B
model_revision: main
torch_dtype: bfloat16

# Data training arguments
dataset_mixer:
  NIKAW/nikaw-collection-v2-qwen2.5-4096: 1.0
dataset_splits:
  - train
  - test
preprocessing_num_workers: 12
# Language column (ensures batches or monolingual)
language_column: language


# SFT trainer config
bf16: true
attn_implementation: flash_attention_2
use_liger_kernel: true

do_eval: true
eval_strategy: "no"
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: NIKAW/qwenus-0.5-v2
hub_strategy: every_save
learning_rate: 1.0e-04
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 4096
max_steps: -1
num_train_epochs: 1
output_dir: data/qwenus-0.5-v2
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 36
push_to_hub: true
remove_unused_columns: true
report_to: 
  - wandb
save_strategy: "steps"
save_steps: 1000
eval_strategy: "steps"
eval_steps: 1000
save_total_limit: 2
seed: 42
warmup_ratio: 0.1
